server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/agileflow_multiplatform_db
    username: postgres
    password: 28092003
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        "[format_sql]": true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  flyway:
    enabled: false
    baseline-on-migrate: true
    locations: classpath:db/migration